### ISSUE TITLE
dateutil.parser issue

### ISSUE THREAD

**Issue by lineojcd** [UCR-Robotics/CED_Detector#2]
follow the instruction guide and run the step of 4.1， got dateutil.parser error
![WX20230209-003042](https://user-images.githubusercontent.com/45730495/217758284-45888c9b-613f-49bd-b8d5-58e3d7b5b330.png)

**Comment by lineojcd** [comment]
I think this is a package version issue. My current version of dateutil is 2.7.1, and I tried to install newer version of the dateutil by 
pip3 install python-dateutil==2.8.2 
the problem then is solved

**Comment by hanzheteng** [comment]
Thanks for pointing out the issue and providing the solution as well.
